name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  

env:
    IMAGE_NAME: sodorpcimage
    IMAGE_TAGS: v1 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        install_latest: [ true, false ]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      # Checkout push-to-registry action github repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:${{ github.run_number }}

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: ./
        id: push
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"

  push_to_contensis:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Contensis block push action
        uses: contensis/block-push@v1
        with:
          alias: staffscc
          block-id: sodor-pc-block
          client-id: ${{ secrets.Z_CLIENT_ID }}
          git-token: ${{ secrets.GIT_TOKEN }}
          image-uri: ${{ env.IMAGE_NAME }}
          project-id: sodorparishcouncil
          shared-secret: ${{ secrets.Z_SHARED_SECRET }}
