---
name: Docker
on:
  schedule:
    - cron: 15 6 * * *
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
env:
  IMAGE_TAGS: build-${{ github.run_number }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }} 
      - name: Contensis block push action
        uses: contensis/block-push@v1
        with:
          alias: staffscc
          block-id: sodor-pc-block-new2
          client-id: ${{ secrets.Z_CLIENT_ID }}
          git-token: ${{ secrets.GIT_PERSONAL }}
          image-uri: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }}
          project-id: sodorparishcouncil
          shared-secret: ${{ secrets.Z_SHARED_SECRET }}
