---
name: Docker
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main
env:
  IMAGE_TAGS: build-${{ github.run_number }}
  IMAGE_NAME: ${{ github.repository }}/${{ github.ref_name }}/app 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
       # login to registry
      - name: Log into container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: vasculum
          password: ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }}
      - name: Contensis block push action
        uses: contensis/block-push@v1
        with:
          alias: staffscc
          block-id: sodor-pc-block-new2
          client-id: ${{ secrets.Z_CLIENT_ID }}
          git-token: ${{ secrets.GIT_TOKEN }}
          image-uri: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAGS }}
          project-id: sodorparishcouncil
          shared-secret: ${{ secrets.Z_SHARED_SECRET }}
